from src.models.album_meta import AlbumMeta
from src.models.artist_albums import ArtistAlbums
from src.models.album_tracks import AlbumTracks
from src.models.artist_info import ArtistInfo
from src.models.artist_songs import ArtistSongs
from src.models.playlist_info import PlaylistInfo
from src.models.plsylist_tracks import PlaylistTracks
from src.models.song_data import SongData
from src.models.song_lyrics import SongLyrics
from src.models.tracks_meta import TracksMeta
